/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PrintSystems;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mihai
 */
public class GeneratorContracte extends javax.swing.JFrame {

    /**
     * Creates new form GeneratorContracte
     */
    public GeneratorContracte() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DFSlogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        EXIT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtContract = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        txtRental = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtLeaseTerm = new javax.swing.JTextField();
        txtCommDate = new javax.swing.JTextField();
        txtEquipCost = new javax.swing.JTextField();
        txtShipping = new javax.swing.JTextField();
        txtTaxes = new javax.swing.JTextField();
        txtLesseeName = new javax.swing.JTextField();
        txtLesseeTitle = new javax.swing.JTextField();
        ADD = new javax.swing.JButton();
        GENERATE = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        UPDATE = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generator de contracte");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/dellimg.png")).getImage());
        setPreferredSize(new java.awt.Dimension(1375, 845));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(1, 136, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        DFSlogo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DFSlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dfs.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRACTS GENERATOR");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 8)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Created by Mhai Andrei Gherghel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(DFSlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DFSlogo, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 130);

        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane1.setViewportView(txtReceipt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(680, 140, 670, 600);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RENT PAYMENT:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 350, 200, 50);

        EXIT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT);
        EXIT.setBounds(1190, 750, 170, 50);

        jLabel3.setBackground(new java.awt.Color(1, 136, 204));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTRACT NUMBER:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 200, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CUSTOMER NAME:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 200, 200, 50);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 250, 200, 50);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LEASE TERM:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 300, 200, 50);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SHIPPING CHARGES:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 500, 200, 50);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("COMMENCEMENT DATE:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 400, 200, 50);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DATE:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 700, 200, 50);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EQUIPMENT COST:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 450, 200, 50);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TAXES & FEES:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 550, 200, 50);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LESSEE NAME:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 600, 200, 50);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("LESSEE TITLE:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 650, 200, 50);

        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtDate);
        txtDate.setBounds(270, 700, 380, 45);

        txtContract.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtContract.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContractActionPerformed(evt);
            }
        });
        getContentPane().add(txtContract);
        txtContract.setBounds(270, 150, 380, 45);

        txtCustName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCustName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtCustName);
        txtCustName.setBounds(270, 200, 380, 45);

        txtRental.setEditable(false);
        txtRental.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRental.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 0, 0), 2));
        getContentPane().add(txtRental);
        txtRental.setBounds(270, 350, 380, 45);

        txtAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtAddress);
        txtAddress.setBounds(270, 250, 380, 45);

        txtLeaseTerm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLeaseTerm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtLeaseTerm);
        txtLeaseTerm.setBounds(270, 300, 380, 45);

        txtCommDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCommDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtCommDate);
        txtCommDate.setBounds(270, 400, 380, 45);

        txtEquipCost.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtEquipCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtEquipCost);
        txtEquipCost.setBounds(270, 450, 380, 45);

        txtShipping.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtShipping.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtShipping);
        txtShipping.setBounds(270, 500, 380, 45);

        txtTaxes.setEditable(false);
        txtTaxes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTaxes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 0, 0), 2));
        getContentPane().add(txtTaxes);
        txtTaxes.setBounds(270, 550, 380, 45);

        txtLesseeName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLesseeName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtLesseeName);
        txtLesseeName.setBounds(270, 600, 380, 45);

        txtLesseeTitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLesseeTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtLesseeTitle);
        txtLesseeTitle.setBounds(270, 650, 380, 45);

        ADD.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        getContentPane().add(ADD);
        ADD.setBounds(660, 750, 170, 50);

        GENERATE.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        GENERATE.setText("GENERATE");
        GENERATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENERATEActionPerformed(evt);
            }
        });
        getContentPane().add(GENERATE);
        GENERATE.setBounds(840, 750, 170, 50);

        CLEAR.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        getContentPane().add(CLEAR);
        CLEAR.setBounds(1015, 750, 170, 50);

        jPanel2.setBackground(new java.awt.Color(1, 136, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(1360, 680));

        UPDATE.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UPDATE.setText("UPDATE FROM DATABASE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        txtID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("GET DATA FROM DATABASE ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UPDATE)
                .addContainerGap(760, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(636, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtID))
                    .addComponent(jLabel15))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 130, 1360, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GENERATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENERATEActionPerformed
        try {
            txtReceipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(GeneratorContracte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GENERATEActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        txtReceipt.setText("");
        txtContract.setText("");
        txtCustName.setText("");
        txtAddress.setText("");
        txtLeaseTerm.setText("");
        txtRental.setText("");
        txtCommDate.setText("");
        txtEquipCost.setText("");
        txtShipping.setText("");
        txtTaxes.setText("");
        txtLesseeName.setText("");
        txtLesseeTitle.setText("");
        txtDate.setText("");
        txtID.setText("");      
    }//GEN-LAST:event_CLEARActionPerformed

    private void txtContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContractActionPerformed
private JFrame frame;
    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Contracts Generator",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {System.exit(0);}
       
    }//GEN-LAST:event_EXITActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        
        double a = Double.parseDouble(txtEquipCost.getText());
        //double b = Double.parseDouble(txtTaxes.getText());
        double b = a * 0.08;
        double c = Double.parseDouble(txtShipping.getText());
        double d = Double.parseDouble(txtLeaseTerm.getText());
        double z;
        z = (a + b + c)/d;
        
        DecimalFormat df = new DecimalFormat("#.##");      
        z = Double.valueOf(df.format(z));
        
        String r = String.valueOf(z);
        String t = String.valueOf(b);
        txtRental.setText(r);
        txtTaxes.setText(t);
        
        
        txtReceipt.append(
                
                "\t\t CONTRACT DETAILS \n\n"+
                "Thank you for choosing Dell Financial Services for your technology financing needs."+ "\n\n" +
                "THIS LEASE AGREEMENT SETS FORTH YOUR RESPONSIBILITIES AND"        + "\n\n" +
                "OBLIGATIONS WITH REGARD TO YOUR LEASE OF THE PRODUCTS."   + "\n\n" + 
                "LEASE NUMBER:\t\t\t" + txtContract.getText() +
                "\n________________________________________________________________________________\n" +
                "CUSTOMER NAME:\t\t\t" + txtCustName.getText() + "\n\n" +
                "ADDRESS:\t" + txtAddress.getText() + "\n\n" +
                 "\n________________________________________________________________________________\n" +       
                "FINANCING TERMS" + "\n\n" +       
                "LEASE TERM:\t\t\t\t" + txtLeaseTerm.getText() + " months" + "\n\n" +
                "RENT PAYMENT:\t\t\t" + txtRental.getText() + " $" + "\n\n" +
                "COMMENCEMENT DATE:\t\t\t" + txtCommDate.getText() + "\n\n" +
                "EQUIPMENT COST:\t\t\t" + txtEquipCost.getText() + " $" + "\n\n" +
                "SHIPPING CHARGES:\t\t\t" + txtShipping.getText() + " $" +"\n\n" +
                "TAXES & FEES:\t\t\t" + txtTaxes.getText() + " $" +"\n\n" +
                "\n________________________________________________________________________________\n" +
                 "AUTHORIZATION" + "\n\n" +         
                "LESSEE NAME:\t\t" +txtLesseeName.getText() + "\n\n" +
                "LESSE TITLE:\t\t\t" +txtLesseeTitle.getText() + "\n\n" +
                "DATE:\t\t\t" + txtDate.getText() + "\n\n" +
                "\n________________________________________________________________________________\n" +
                "Thanks again for choosing Dell Financial Services!" +  "\n" +
                "If you have any questions regarding the documentation," +  "\n" +
                "please free to contact me."    + "\n" +
                "Mike Ford"        + "\n" +
                "mike_ford@dell.com" + "\n" +
                "\n________________________________________________________________________________\n"  +        
                "\t TERMS AND CONDITIONS OF LEASE \n\n"     + "\n" +
                "1. NO WARRANTIES: WE ARE LEASING THE PRODUCTS TO YOU 'AS-IS'. " + "\n" +
                "YOU ACKNOWLEDGE THAT WE DO NOT MANUFACTURE OR SUPPLY THE " + "\n" +
                "PRODUCTS, WE DO NOT REPRESENT THE MANUFACTURER OR SUPPLIER" + "\n" +
                "AND YOU HAVE SELECTED THE PRODUCTS AND THE SUPPLIER BASED" + "\n" +
                "ON YOUR OWN JUDGMENT. WE MAKE NO WARRANTIES OF ANY KIND,"+ "\n" +
                "EXPRESS OR IMPLIED, INCLUDING THE MERCHANTABILITY OR"+ "\n" +
                "FITNESS FOR ANY PARTICULAR PURPOSE OF THE PRODUCT OR " + "\n" +
                "ANY SERVICES. PROVIDED NO EVENT OF DEFAULT HAS OCCURRED"+ "\n" +
                "AND IS CONTINUING, WE HEREBY ASSIGN TO YOU FOR THE TERM " + "\n" +
                "OF THE LEASE ALL WARRANTIES MADE TO US BY SUPPLIER, " + "\n" +
                "MANUFACTURER, AND ANY SERVICE PROVIDER TO YOU, AND YOU "+ "\n" +
                "AGREE THAT YOU WILL MAKE ALL CLAIMS OF ANY KIND RELATING "+ "\n" +
                "TO THE PRODUCTS OR SERVICES AGAINST SUCH SUPPLIER,"       + "\n" +
                "MANUFACTURER, AND/OR SERVICE PROVIDER." + "\n" +
                         "\n" +
                "2. ACCEPTANCE; ENTIRE AGREEMENT; DELIVERY; ELECTRONIC "+ "\n" +
                "SIGNATURES AND RECORDS; BY SIGNING THIS LEASE: "+ "\n" +
                "(a) YOU ACKNOWLEDGE THAT YOU HAVE RECEIVED, READ, "+ "\n" +
                "UNDERSTAND AND AGREE TO ALL OF THE TERMS AND CONDITIONS. "+ "\n" +
                "(b) YOU AGREE THAT THIS LEASE IS A NET LEASE AND YOU "+ "\n" +
                "CANNOT TERMINATE OR CANCEL AND UPON ACCEPTANCE OF THE "+ "\n" +
                "PRODUCTS YOU HAVE AN UNCONDITIONAL OBLIGATION TO MAKE "+ "\n" +
                "ALL PAYMENTS UNDER THIS LEASE AND YOU CANNOT WITHHOLD,"+ "\n" +
                "SETOFF OR REDUCE SUCH PAYMENTS FOR ANY REASON; "+ "\n" +
                "(c) YOU AGREE THAT THE PRODUCTS WILL BE USED FOR "+ "\n" +
                "BUSINESS PURPOSES ONLY AND NOT FOR PERSONAL, FAMILY OR"+ "\n" +
                "HOUSEHOLD PURPOSES; "+ "\n" +
                "(d) YOU CONFIRM THAT THE PERSON SIGNING THIS LEASE FOR"+ "\n" +
                "YOU HAS THE AUTHORITY TO DO SO;"+ "\n" +
                        
                        
                "\n________________________________________________________________________________\n"     
                        
                );
        
    }//GEN-LAST:event_ADDActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dfslogin", "root","");
            String sql = "SELECT ID,CONTRACT,CUSTNAME,ADDRESS,LEASETERM,COMMENCEMENTDATE,EQUIPCOST,SHIPPING,LESSEENAME,LESSEETITLE,DATE FROM contracte WHERE ID =?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,txtID.getText());

            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                String CONTRACT = rs.getString("CONTRACT");
                txtContract.setText(CONTRACT);
                String CUSTNAME = rs.getString("CUSTNAME");
                txtCustName.setText(CUSTNAME);
                String ADDRESS = rs.getString("ADDRESS");
                txtAddress.setText(ADDRESS);
                String LEASETERM = rs.getString("LEASETERM");
                txtLeaseTerm.setText(LEASETERM);
                String COMMENCEMENTDATE = rs.getString("COMMENCEMENTDATE");
                txtCommDate.setText(COMMENCEMENTDATE);
                String EQUIPCOST = rs.getString("EQUIPCOST");
                txtEquipCost.setText(EQUIPCOST);
                String SHIPPING = rs.getString("SHIPPING");
                txtShipping.setText(SHIPPING);
                String LESSEENAME = rs.getString("LESSEENAME");
                txtLesseeName.setText(LESSEENAME);
                String LESSEETITLE = rs.getString("LESSEETITLE");
                txtLesseeTitle.setText(LESSEETITLE);
                String DATE = rs.getString("DATE");
                txtDate.setText(DATE);

            }

            con.close();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_UPDATEActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneratorContracte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneratorContracte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneratorContracte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneratorContracte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneratorContracte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton CLEAR;
    private javax.swing.JLabel DFSlogo;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton GENERATE;
    private javax.swing.JButton UPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCommDate;
    private javax.swing.JTextField txtContract;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEquipCost;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLeaseTerm;
    private javax.swing.JTextField txtLesseeName;
    private javax.swing.JTextField txtLesseeTitle;
    private javax.swing.JTextArea txtReceipt;
    private javax.swing.JTextField txtRental;
    private javax.swing.JTextField txtShipping;
    private javax.swing.JTextField txtTaxes;
    // End of variables declaration//GEN-END:variables
}
