/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginSystems;

import PrintSystems.GeneratorContracte;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.ws.BindingProvider;

/**
 *
 * @author mihai
 */
public class LoginSystem extends javax.swing.JFrame {

    /**
     * Creates new form LoginSystem
     */
    public LoginSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jBtnExitLogin = new javax.swing.JButton();
        jBtnLogin = new javax.swing.JButton();
        jBtnClearLogin = new javax.swing.JButton();
        DFSlogo1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contracts Generator LOGIN");
        setBackground(new java.awt.Color(1, 136, 204));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/dellimg.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(1, 136, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Contracts Generator Login System", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 48))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(1050, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setText("USERNAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 270, 77));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 270, 82));

        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 470, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 470, -1));

        jBtnExitLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jBtnExitLogin.setText("EXIT");
        jBtnExitLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnExitLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 180, -1));

        jBtnLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jBtnLogin.setText("LOGIN");
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 200, -1));

        jBtnClearLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jBtnClearLogin.setText("CLEAR");
        jBtnClearLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnClearLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 180, -1));

        DFSlogo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DFSlogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dfs.png"))); // NOI18N
        jPanel1.add(DFSlogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 110, 70));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 8)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Created by Mhai Andrei Gherghel");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 610, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Please use the credentials received on your e-mail after enrolling!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 610, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private JFrame frame;
    private void jBtnExitLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitLoginActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Login System",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {System.exit(0);}
    }//GEN-LAST:event_jBtnExitLoginActionPerformed

    private void systemExit()
    {
        WindowEvent iClose = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(iClose);
    }
    
    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dfslogin", "root","");
            String sql = "Select * from login where username=? and password=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,txtUsername.getText());
            pst.setString(2,txtPassword.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                
                 systemExit();
                 GeneratorContracte info = new GeneratorContracte();
                 info.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid login detail", "Login System", JOptionPane.ERROR_MESSAGE);
                txtUsername.setText(null);
                txtPassword.setText(null);
                txtUsername.grabFocus();
            }
            con.close();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        //varianta hardcoded:
//        String Username = txtUsername.getText();
//        String Password = txtPassword.getText();
//        
//        if (Username.contains("dellops")&& Password.contains("dellpass"))
//        {
//            txtUsername.setText(null);
//            txtPassword.setText(null);
//            
//            systemExit();
//            GeneratorContracte info = new GeneratorContracte();
//            info.setVisible(true);
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(null, "Invalid login detail", "Login System", JOptionPane.ERROR_MESSAGE);
//            txtUsername.setText(null);
//            txtPassword.setText(null);
//            txtUsername.grabFocus();
//        }
    }//GEN-LAST:event_jBtnLoginActionPerformed

    private void jBtnClearLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearLoginActionPerformed
         txtUsername.setText(null);
         txtPassword.setText(null);
            txtUsername.grabFocus();
    }//GEN-LAST:event_jBtnClearLoginActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DFSlogo1;
    private javax.swing.JButton jBtnClearLogin;
    private javax.swing.JButton jBtnExitLogin;
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
